### PR TITLE
Fix appcontext

### LINKED ISSUE #44: Flask 2.2 breaks Executor
The recent Flask 2.2 release throws all kinds of context errors when submitting a job:
```
  File /site-packages/flask/ctx.py, line 256, in pop
    _cv_app.reset(self._cv_tokens.pop())
ValueError: <Token var=<ContextVar name='flask.app_ctx' at 0x7fb4152020b0> at 0x7fb4054b1f50> was created in a different Context
```

### PR DESCRIPTION
**Pull request by dchevell**
Fixes #44

Makes pushing a new app context the new default instead of using deprecated methods to copy the existing context.

Preserves pushing `g` to new context by making a copy of this object and attaching it to a new context.

### CODE REVIEW

**Comment by dchevell** [comment]
Note: removing coveralls, will likely migrate to codecov for coverage reports

**Comment by dchevell** [comment]
@okke-formsma curious if you wanted to look at this, it aims to fix #44 by making your push_app_context addition the default behaviour, and adds support to that method for preserving the contents of `g`. Those tests, and your original flask-sqlalchemy tests, now pass using the one approach, and and if you have the time, I’d appreciate your feedback

**Comment by okke-formsma** [comment]
Oh wow this is a blast from the past! https://github.com/dchevell/flask-executor/issues/15 from 2019 :)

I haven't worked on any flask projects since 2019 so I don't feel very confident to give my opinion on this unfortunately. Thanks for informing me though :)

**Comment by christopherpickering** [comment]
Thanks @dchevell this fixed the problem for my app.

**Pull request merged**
